### ISSUE TITLE
"Textbox" shape isn't showing in XWiki PDF export

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#100]
Steps to reproduce:

1. Create a new Diagram
2. Add the Textbox shape (with Heading)
3. Click Save & View
4. Access More actions > Export > Export as PDF
5. Deselect all options > Export

Expected results: The shape / text is shown properly.

Actual results: "[Not supported by viewer]" appears instead of the shape / text.

Environment: XWiki 8.4.5 with Chrome 78 and Diagram Application (Pro) 1.12

![Textbox](https://user-images.githubusercontent.com/40691112/70531660-056b1100-1b5e-11ea-8d42-d8d4dca2ca5a.jpg)

![PDFExportTextbox](https://user-images.githubusercontent.com/40691112/70531664-08660180-1b5e-11ea-951a-33b369fd8217.jpg)

**Comment by mflorea** [comment]
We need to debug the [createAlternateContent](https://github.com/xwikisas/application-diagram/blob/application-diagram-1.12/application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml#L454) function. Currently the expected behavior is to view the HTML inner text in PDF export (as a fallback for the SVG foreign object which is not supported by Apache FOP).

**Comment by oanalavinia** [comment]
The fix is just a first version of how inserted text is seen in xwiki pdf export. The resulted pdf will not be 100% accurate (e.g. the alignment will be center, regardless of what was set)

An example of differences that can be seen:

**Created diagram:**
![created_diagram](https://user-images.githubusercontent.com/22794181/73446729-f3d80580-4365-11ea-8ea8-7ac183a45613.png)
**Exported diagram**
![exported_diagram](https://user-images.githubusercontent.com/22794181/73446745-005c5e00-4366-11ea-93e8-209ea40e83ba.png)

Besides the rendering of basic text shapes (simple short text, headers) this fix also manages lists (without their corresponding numbers or bullets)
