### ISSUE TITLE
Text links aren't showing in XWiki PDF export

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#101]
Steps to reproduce:

1. Create a new Diagram
2. Add some text shapes
3. Select a piece of text
4. Click on the Link... button below Insert from the right panel
5. Select a wiki page > Apply
6. Select another piece of text
7. Click on the Link... button below Insert from the right panel
8. Select External and paste an URL eg. https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/colorful-of-dahlia-pink-flower-in-beautiful-garden-royalty-free-image-825886130-1554743243.jpg
9. Click Save & View
10. Access More actions > Export > Export as PDF
11. Deselect all options > Export

Expected results: The links appear.

Actual results: Links don't appear.

Environment: XWiki 8.4.5 with Chrome 78 and Diagram Application (Pro) 1.12

![DiagramExportInternalExternal](https://user-images.githubusercontent.com/40691112/70535516-e7091380-1b65-11ea-9720-8fd2f5c083c5.jpg)

![PDFExportInternalExternal](https://user-images.githubusercontent.com/40691112/70535522-e96b6d80-1b65-11ea-9f64-10667b9f6c8e.jpg)

**Comment by mflorea** [comment]
The reason for this issue is that:
* Apache FOP doesn't support HTML embedded in SVG (through foreign objects)
* The fall back done inside the SVG with a switch is currently using the HTML inner text. This means that viewers that don't support embedded HTML currently fallback on the inner text (no link)

The solution for this, apart from waiting for Apache FOP to add support for embedded HTML, is to improve the code that does the fallback. This is done by [``createAlternateContent``](https://github.com/xwikisas/application-diagram/blob/application-diagram-1.12/application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml#L454) whose goal is to convert the HTML to SVG as much as possible. The easiest, which is currently implemented, is to take the inner text from the HTML and generate an SVG text element. Maybe we can also convert the HTML links to SVG links.

**Comment by oanalavinia** [comment]
Following #113 , adding links to just a part of text from a paragraph will still not work, and only the text will be shown in XWiki PDF export.
