### ISSUE TITLE
Links in the diagram content are not updated when the linked page is moved/renamed

### ISSUE THREAD

**Issue by CamiAndrei** [xwikisas/application-diagram#110]
The links from the diagram content are not updated when the linked content is moved or renamed.
Steps to reproduce:
* Create a page A1
* Insert a link to A1 in a diagram
* Rename/move A1 page
Results:
The links in the diagram are not updated.

**Comment by mflorea** [comment]
First we need to **detect when a page is renamed**. For this we need to write an event listener. On XWiki 11.1RC1+ we can use the dedicated page rename events. On older versions we need to do some hacks. @lucaa might be able to help us with that. Note that if we want to use the dedicated rename events without increasing the minimum XWiki version we need to use reflection and do some hacks.

Once we are notified when a page is renamed we need to **determine which diagram pages have links to the renamed page**. This can be done on each rename with a database query, or we could try to use the **backlinks** table, but for this we would need another event listener that updates the backlinks whenever a diagram is saved (by adding the links from the saved diagram).

Once we know which diagrams have to be updated we need to modify their XML content. The best for this would be to use a stream-based XML parser / serializer because we don't need to load the entire diagram XML in memory, we just need to get to the XML element that holds the link and modify some attribute value.

In any case, this processing should be done **asynchronously**. It shouldn't block the page rename. It's fine if the diagrams are updated "slowly" in a background thread.

**Comment by lucaa** [comment]
@mflorea Here is how @slauriere (and myself?) hacked this in the past https://github.com/xwiki-contrib/application-page-relations/blob/application-page-relations-2.4/application-page-relations-api/src/main/java/org/xwiki/contrib/pagerelations/internal/PageRelationsRenameEventListener.java#L69 (listening to create and then checking the context by the name or something). I think it was somewhat validated that it's the good way to know if the creation is part of a rename or a regular create.

**Comment by mflorea** [comment]
Thanks @lucaa , this is very helpful.

**Comment by oanalavinia** [comment]
For diagrams created before the fix version, an additional save on each diagram page will be needed (to mark the page as a backlink)
