### ISSUE TITLE
The content in the "Text" shape isn't showing in XWiki PDF export when there is text separated on different rows by Enter

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#118]
Steps to reproduce:

1. Create a new Diagram
2. Add a Text shape
3. Add some text on different rows separated by enter (like a list) 
3. Click Save & View
4. Access More actions > Export > Export as PDF
5. Deselect all options > Export

Expected results: The shape / text is shown properly.

Actual results: The text in the shape doesn't appear at all.

Environment: XWiki 8.4.5, Cloud (11.3.6), 11.10.3 with Chrome 80 and Diagram Application (Pro) 1.12.2

![8 4 5](https://user-images.githubusercontent.com/40691112/74935604-33d45a80-53f1-11ea-8545-5bfda05ee82f.jpg)

![8 4 5 PDF Export](https://user-images.githubusercontent.com/40691112/74935617-36cf4b00-53f1-11ea-9a4e-65403f1e6500.jpg)

![Cloud](https://user-images.githubusercontent.com/40691112/74935638-42227680-53f1-11ea-9550-83ab3a4b6c49.jpg)

![Cloud Export](https://user-images.githubusercontent.com/40691112/74935650-451d6700-53f1-11ea-802a-3c04f4e8015c.jpg)

![11 10 3](https://user-images.githubusercontent.com/40691112/74935621-3afb6880-53f1-11ea-814f-48d341b48915.jpg)

![11 10 3 Export](https://user-images.githubusercontent.com/40691112/74935661-49498480-53f1-11ea-8d03-39f990dbe5f9.jpg)

**Comment by oanalavinia** [comment]
Since #113 the text is now showing in the generated pdf, but arranged in a line, having words glued to one another since _newline_ is not seen as a separator

Workaround for some cases: for a similar result, at the end of a line a _space_ should also be added and the size of the container should also be adjusted in the limits of the lines (to simulate the same result with word-wrap) 

Edit mode:
![editMode](https://user-images.githubusercontent.com/22794181/78544018-2f79ca80-7802-11ea-97f7-7d1879a1537e.png)
PDF result:
![pdfExport](https://user-images.githubusercontent.com/22794181/78544028-343e7e80-7802-11ea-8168-f97011eeac84.png)
