### ISSUE TITLE
No PNG or SVG is created while Saving a Diagram on IE 11

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#135]
Steps to reproduce:

1. Create a new diagram with some shapes
2. Click on the **Save** button
3. Click on the Cancel button

Expected results: The diagram is saved and the SVG and PNG images are created in the Attachments section.

Actual results: The diagram is saved but nothing appears in the Attachments section.

Environment: XWiki 11.10.4 with MySQL 5.7 and IE 11, Diagram Application (Pro) 1.13 

![IE11Save](https://user-images.githubusercontent.com/40691112/79159346-912ccc80-7de0-11ea-8397-2ceec3a466e0.jpg)

![IE11ResultsAfterSave](https://user-images.githubusercontent.com/40691112/79159366-9a1d9e00-7de0-11ea-9d11-5434e5b70ce4.jpg)

**Comment by oanalavinia** [comment]
**Note**: this issue is related to #59 and as is explained here the PNG attachment **will not be save** when using IE, but the SVG attachment will be in place (XWiki PDF Export will fallback to the SVG even though this is not what was selected by the user)

This comment gives more details about the reason behind this issue https://github.com/xwikisas/application-diagram/issues/59#issuecomment-532119659
