### ISSUE TITLE
Can't export a diagram as PDF

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#270]
Preconditions: Have a diagram page created with added shapes.

1. Edit the diagram page
2. Click on File > Export as > PDF...
3. Click on Export
4. Choose a name for the diagram
5. Click on Download

Expected results: The diagram is exported as PDF.

Actual results:  The diagram isn't exported

![PDFExport](https://github.com/xwikisas/application-diagram/assets/40691112/c40fd7cb-7683-4685-980d-26b69d5fd2d3)

Environment: Windows 11, Chrome 125. Cloud XWiki 15.10.8, Diagram Application (Pro) 1.20.4

**Comment by mflorea** [comment]
Note that here are two ways you can export a diagram to PDF:

* From the diagram editor: the diagram is sent to a remote service to perform the conversion to PDF. This remote service is configurable, but by default diagrams.net is used which we don't control. Such a remote service can obviously be down, have access limits, misbehave or change its behavior in a way that is not backwards compatible with our version of draw.io
* from the page view mode: the diagram is exported to PDF by us, which is normally more reliable

So we need to check:

* if the failure is temporary or related to some service limits
* if the failure is caused by some specific diagram content
* if the failure is caused by a change in the service URL or expected parameters
* if the failure is caused by a change in the service implementation that is not backwards compatible with our version of draw.io

**Comment by oanalavinia** [comment]
I am still investigating on this issue, couldn't find the root cause yet.

It's important to mention that the structure of the request altered a little on newer drawio versions. For example there are more parameters [for this method](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/diagramly/EditorUi.js#L2250) and these could be required for the request to work. So a drawio upgrade seems necessary anyway. 
On another note, I did tried locally to apply these changes and the export still doesn't work, but I might be missing something (there are a lot of changes to consider). Unfortunately, the request response is not giving that much information.
I would suggest to go on with the drawio upgrade and that come back at this issue

Until this is fixed, it's important to know that `File -> Print` could be used as a **workaround**, and it's actually safer since you don't send your data to an external server. Check https://www.drawio.com/blog/export-pdf#secure-pdf-generation

**Comment by ilieandriuta** [comment]
Issue reproduced too on XWiki 16.4.0 using Diagram Application (Pro) 1.20.5.

**Comment by snazare** [comment]
proposal: when clicking on File - Export As - PDF use the File -> Print service.

**Comment by ane-gabriela** [comment]
@snazare  Tested on XWiki 15.10.10 with version 1.21-rc-1, extension id com.xwiki.diagram:application-diagram (drawio24.5.5) - got the same result as above, the diagram is not exported

Steps to reproduce:

1. While editing the Diagram click on File > Export as > PDF... >Export
2. Select a name for the exported diagram
3. Select Device / Download / Open in New Window ![Option](https://github.com/user-attachments/assets/37084cb6-c485-4a04-b395-ed075331f6b5)
4. Click on the Save or OK button depending on the selection made previously

Actual results: No matter the selection made the result is the same - no diagram appears in the export

![DownloadResult](https://github.com/user-attachments/assets/1befb9e9-fa05-442a-8d11-5e7ea1ef3071)

**Comment by snazare** [comment]
to be handled in #288

**Comment by ane-gabriela** [comment]
Issue resolved by https://github.com/xwikisas/application-diagram/issues/288#issuecomment-2517164464

"remove the "Export as PDF" option from the export section, rename the "Print" button to "Print / Export as PDF," and add a tooltip to clarify the button's functionality when hovered over."
