### ISSUE TITLE
Diagram page PDF export does not contain the diagram 

### ISSUE THREAD

**Issue by slauriere** [xwikisas/application-diagram#29]
## Steps to reproduce

* Create a simple diagram and save it
* Hit the button "More actions > Export > PDF"

## Behaviour

* The diagram is not present in the generated PDF, which is not expected.

## Configuration

* XWiki 11.1
* Diagram Pro 1.6.2

**Comment by oanalavinia** [comment]
This issue is reproducing only for private documents (i.e. having 'Prevent unregistered users from viewing pages, regardless of the page or space rights' checked on Rights page from XWiki Preferences).
More details are also on the JIRA issue [https://jira.xwiki.org/browse/XADIAGRAM-45](XADIAGRAM-45)

**Comment by oanalavinia** [comment]
For this fix to work after the upgrade on already finished diagrams, the user still needs to edit the diagram one more time before the export

**Comment by mflorea** [comment]
@oanalavinia indeed, good point. It's not easy to write a (server-side) migration at this point because the diagram thumbnail is generated on the client side when the diagram is saved (we would have to load all the diagrams in edit mode and save them..). I think it's acceptable to ask the user to re-save the diagram if the PDF export is not good.

**Comment by oanalavinia** [comment]
Considering this jira issue https://jira.xwiki.org/browse/XWIKI-14204 there are some xwiki versions on which the diagram image attachment won't be added at creation step, so neither the page pdf export will work until an extra edit and save will be performed on the diagram.
