### ISSUE TITLE
PDF export seems to expose possibly restricted content to an external service

### ISSUE THREAD

**Issue by slauriere** [xwikisas/application-diagram#30]
When exporting a diagram from the diagram editor (menu "File > Export as > PDF"), a request is sent to https://exp.draw.io/ – which may expose the page content to an external service without the user consent, doesn't it?

**Comment by mflorea** [comment]
I added a configuration section to allow using a different diagram export server. In order to setup your own export server you need to look at https://github.com/jgraph/draw-image-export2 . Docker images can be found at https://github.com/jgraph/docker-drawio .

I opened [XWPLT-2913](https://jira.xwikisas.com/browse/XWPLT-2913) to ask the XWiki SAS infra team to host a diagram export server for our paid customers.
