### ISSUE TITLE
Diagram is not displayed

### ISSUE THREAD

**Issue by CamiAndrei** [xwikisas/application-diagram#40]
Steps to reproduce with no license added:
1. Login with superadmin
2. Add a diagram
3. Login with a simple user or admin
4. Go to diagram 
The diagram is not displayed. This is a possible result after the license expires and the users are not able to see the license.

![Screenshot from 2019-05-30 14-20-13](https://user-images.githubusercontent.com/12369283/58630627-a98b1a00-82e8-11e9-9238-8be938b12652.png)

**Comment by mflorea** [comment]
The latest version of the [Licensing Application](https://github.com/xwikisas/application-licensing/pull/60) will display a message when the page cannot be properly displayed because a required license is missing. I don't see what we could do otherwise. The user owns the diagram he created (he can do whatever he wants with the diagram page and the diagram "code") but in order to view the **rendered** diagram he needs to have a license.
