### ISSUE TITLE
Page title starting with L creates a nonfunctional diagram page

### ISSUE THREAD

**Issue by AndreeaDCA** [xwikisas/application-diagram#5]
Steps to reproduce:
1. Create a diagram page 
2. Name it with a word starting with "L"
3. Click on Create.

Expected result: a new diagram page appears with editing options available.
Actual result: a new diagram page appears with a pop up error as in the image below.

![diagram app error loading file](https://user-images.githubusercontent.com/36840106/43769513-90c35788-9a42-11e8-931a-3a16cd4fbcd0.JPG)

4. Close the error pop up.
5. Save&View the page.

Result: the saved page includes a continuous loading loop, with the diagram not being visible. See the image below.

![diagram app error loading loop 2](https://user-images.githubusercontent.com/36840106/43770029-de07b5ce-9a43-11e8-897d-723a577ed8d7.JPG)

Environment: Windows 10, XWiki Jetty HSQLDB 10.5, Google Chrome 68.0.3440.84 (64-bit)
Issue opened on Jira as well: https://jira.xwiki.org/browse/XADIAGRAM-53

**Comment by mflorea** [comment]
Thanks for catching this. The issue is that we use the page title as the diagram "file name" and it appears that draw.io uses the first letter of the file name as "storage" indicator. In this case capital L means "local store" so it tries to load the file from the browser local storage.. There are other storage types..

* R means raw file
* G means Google Drive
* D means Dropbox
* etc.

I guess I'll just prefix the file name with "X" then :) .
