### ISSUE TITLE
Hide 'Export as HTML' submenu

### ISSUE THREAD

**Issue by arcilli** [xwikisas/application-diagram#53]
After a few discussions with @mflorea, we decided to hide 'export as html' option because it's not bringing a lot of advantages between other options (SVG/XML format).

**Comment by mflorea** [comment]
Moreover, the HTML export doesn't work fine ATM and I'm not sure it's worth spending time fixing it since it's not easy (@arcilli already spent some time investigating) and I don't think this feature is used that much. Of course, we can later re-evaluate this in case we'll see requests for this feature.
