### ISSUE TITLE
Sometimes an error message appears when saving the diagram

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#59]
I could't find a clear pattern for this issue but while testing the Diagram app I've noticed that sometimes after I add a shape and click Save & View the "Error when saving the diagram as an image attachment" message appears.

![Screenshot_1](https://user-images.githubusercontent.com/40691112/63841245-22068300-c98b-11e9-90f9-3b5a0114ce68.jpg)

There is no error message in the XWiki console. If clicked again, the diagram is saved properly.

This happened on Chrome 76 and Edge 18 on XWiki 10.11.8 and 8.4.5

**Comment by mflorea** [comment]
@oanalavinia could you look into this when you have some time? Thanks.

**Comment by oanalavinia** [comment]
@mflorea Sure.

**Comment by oanalavinia** [comment]
There is no valid way to get the image attachment in IE without a SecurityError. As a result, for these cases the pdf export, when having a private wiki, won't work (the changes done to the diagram will be saved, without saving the attachment).
* in case it will be a requested feature, we could save the diagram as an svg attachment (only when toBlob is not defined) and use it for export. The problem with this approach is that inserted text won't be displayed (because FOP is not supporting html inside svg)
* investigation: even if it is to convert manually the canvas to Blob, it will still throw a SecurityError; using 'drawImage' for inserting the image into the canvas, is tainting it in the POV of IE, not having the possibility to get dataUrl after; a discussion on this subject could be found in here https://stackoverflow.com/questions/27230293/how-to-draw-an-inline-svg-in-dom-to-a-canvas/33227005#33227005

**Comment by ane-gabriela** [comment]
Tested on 8.4.5, 10.11.9 (Cloud) and 11.7 with Edge 18 and IE 11 -  same results, the attachment is not saved anymore.

**Comment by mflorea** [comment]
@ane-gabriela but the diagram itself is saved right? I mean, there's no error message anymore right?

**Comment by ane-gabriela** [comment]
The diagram in saved in the XWiki page. Just the attachment is not present anymore.

**Comment by mflorea** [comment]
> Just the attachment is not present anymore.

This is the expected behavior (for now) on IE. @oanalavinia explained above the reason.

**Comment by ane-gabriela** [comment]
Yes, she mentioned IE. My comment above was to mention that it is the same behavior on Edge 18 (to have this info for future references)
