### ISSUE TITLE
Uncategorized shapes cannot be exported as PNG/JPEG

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-diagram#7]
Please see the following [JIRA](https://jira.xwiki.org/browse/XADIAGRAM-43) issue.

**Comment by mflorea** [comment]
The same happens with external images inserted into the diagram. In fact the shapes you find with the search are external images. The problem is that the image export is performed using the [Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) and drawing external images (from a different domain) on a canvas [has limitations](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images#Using_images_from_other_domains). The domain where the external image is hosted needs to provide [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) headers. In order to avoid this limitations draw.io tries to load the external images through a proxy located on the same domain from where the draw.io code is loaded. ATM we don't configure the proxy URL, so the Diagram Application ends up requesting something like:

    /xwiki/bin/edit/Diagram/Test/proxy?url=https%3A%2F%2Fcdn0.iconfinder.com%2Fdata%2Ficons%2Ffire%2F106%2Fspark-128.png

In order to fix this issue we would need to implement a proxy and configure it. For instance:

    var PROXY_URL = new XWiki.Document('DiagramProxy', 'Diagram').getURL('get');

which would be called by

    /xwiki/bin/get/Diagram/DiagramProxy?url=https%3A%2F%2Fcdn0.iconfinder.com%2Fdata%2Ficons%2Ffire%2F106%2Fspark-128.png

The issue is that in order to implement this proxy we need to ether use Groovy (and thus require programming rights) or use Java (and thus prevent the installation on a subwiki by a local admin).

Moreover, we'd have to limit the access to this proxy for security reasons.

**Comment by mflorea** [comment]
I've done a quick/simple implementation of the proxy using Groovy in the end. This means that the ``Diagram.DiagramProxy`` page needs to be saved with programming rights.
