### ISSUE TITLE
Zoom a diagram in view mode creates a vertical scrollbar

### ISSUE THREAD

**Issue by js-ddev** [xwikisas/application-diagram#71]
On the 1.8 release, in view mode when zooming into the diagram and when the width of the content window is reached, a vertical scrollbar appears as if the diagram took 101% of the content height.
The height seems always defined proportionally to the width, maybe you could set it to "auto" ?

Tested in XWiki 11.3.4, on Firefox and Chrome last version.

![diagram-vertical-scrollbar](https://user-images.githubusercontent.com/27762774/65500775-19d53100-dec0-11e9-9d6e-a4272705d344.png)

**Comment by mflorea** [comment]
@js-ddev this behavior is somehow normal. You zoom until the diagram doesn't fit horizontally within its container and thus the browser adds the horizontal scroll bar. But the horizontal scroll bar is added within the diagram box so it takes vertical space from the diagram (5-10 pixels). This means the horizontal scroll bar could hide something from the diagram. The browser adds the vertical scroll bar in order to allow you to see the content that may have been hidden by the horizontal scroll bar.

I could hide the vertical scroll bar completely but I'm not sure this is desired in all use cases. It's OK when you view the diagram page, because the XWiki skin doesn't limit the page height, but the diagram could also be included in a modal or in a table or anywhere else where the height is limited.

Note that Confluence has the same issue https://www.youtube.com/watch?v=HBZeREVx0Wc , because the zoom is performed by draw.io not by our code.
