### ISSUE TITLE
Print preview feature doesn't display Diagram

### ISSUE THREAD

**Issue by js-ddev** [xwikisas/application-diagram#72]
In the 1.8 release of the application, when using the Print preview in the XWiki page menu button the diagrams are not shown.
Yet they can be printed with the page, and are shown using browser's print preview feature.
Tested in Firefox and Chrome, last releases, on Ubuntu:
![Diagram-XWiki-preview](https://user-images.githubusercontent.com/27762774/65501373-2dcd6280-dec1-11e9-86c1-5f7ec55d82c5.png)
![Diagram-browser-preview](https://user-images.githubusercontent.com/27762774/65501374-2dcd6280-dec1-11e9-8c95-e1b9c6d7e2fc.png)

**Comment by mflorea** [comment]
There are 2 sides of the problem:
* ``print.vm`` (activated by ``xpage=print``) doesn't include ``javascript.vm`` and so the JavaScript of the diagram viewer is not loaded in print preview, which is probably expected since PDF export can't use the JavaScript code
* The diagram view sheet only checks for export action.
