### ISSUE TITLE
PDF export from wiki page menu not working if diagram page doesn't have attachment

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-diagram#84]
When trying to export a diagram that doesn't have a file in the attachments section, the PDF exported from the wiki page menu does not include the diagram.

Tested on Chrome, Version 77.0, Windows 10 Pro

Current workaround was to add a modification to the diagram and then to save it in order to have an attachment appear in the dedicated section and to be able to see the diagram in a PDF export.

![image](https://user-images.githubusercontent.com/36840106/68032364-37b76200-fcc6-11e9-838b-378ee9fe0c32.png)

**Comment by mflorea** [comment]
This actually happens on closed wikis only. On open wikis, when the image attachment is missing the export falls-back on the SVG export, which is not perfect, but the diagram should appear.

**Comment by oanalavinia** [comment]
More details from the wider issue #29. On this comment https://github.com/xwikisas/application-diagram/issues/29#issuecomment-521148146 it is specified that the fix is working only with an extra editing (changes + save) step for diagrams created before 1.7

**Comment by mflorea** [comment]
The diagram SVG has been moved from the diagram object to an attachment named ``diagram.svg`` which is always generated by the application (IE included). Existing diagrams are migrated when the Diagram Application is upgraded. If you delete the ``diagram.svg`` attachment by mistake then you need to edit and save the diagram page in order to regenerate it.
