### ISSUE TITLE
The link to a wiki page isn't working in PDF export, from Diagram Menu

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#94]
Steps to reproduce:

1. Create a diagram
2. Add some text shapes
3. Select the text
4. Add a link to a wiki page
5. Click on File > Export as > PDF... > Export > Open in New Window
6. Click on the links

Expected results: The links are working.

Actual results: It appears as the text is shown as a link but there is no link to go to.

Note: The links work when adding a link with a shape, from the plus sign.

![ExportLinks](https://user-images.githubusercontent.com/40691112/69808324-e7152500-11ef-11ea-85e2-bd3043927c8e.jpg)

**Comment by mflorea** [comment]
Indeed I haven't handled these type of links. I think they are stored as HTML links in the shape (node) label. We need to  extend the ``diagram-graph-xml-filter`` module from ``Diagram.DiagramSheet`` to add support for filtering these type of links. This issue is more how to do it without duplicating code. Code refactoring might be needed.
